### ISSUE TITLE
File associations for .TS

### ISSUE THREAD

**Issue by arifpedia** [lelegard/qtlinguist-installers#10]
I think a good idea by adding an option to integrate `.TS` files.

**Comment by lelegard** [comment]
Hi,

This is a good idea. In principle. However, ".ts" is an extremely poor choice from Qt. ".ts" is too simple and is used by other types of files. For instance, ".ts" is used for MPEG Transport Stream files, containing audio/video/data multiplex. By default, when VLC Media Player is installed, ".ts" is associated with VLC to view video tracks.

If Qt had chosen extensions like ".qtrans" or something very specific, I would have had already associated it with Qt Linguist. However, I consider that hijacking an already registered extension like ".ts" would be too damaging and many people would blame me for that.

So, I won't do it, sorry.
