### ISSUE TITLE
Mutlilanguage interface for QT Linguist (add linguist_xx.qm file)

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#11]
@lelegard 

Could you please for all languages included in the installer, where i s possible and teh relative file available, add to your installation package also all linguist-xx.qm (where xx is the language code) to enable the QT Linguist start in native language file?

Current languages included in the installer

- QT sdk language - bg/ca/cs/da/de/es/fr/fi/gd/he/hu/it/ja/ko/lv/pl/ru/sk/uk

Theese are the linguist_xx language available to add to the installer

Available here: http://l10n-files.qt.io/l10n-files/

- Linguist language available bg/cs/da/de/es/fr/hu/ja/ko/pl/ru/sk/uk

or then you can find into translate sub-folder of the folder that depend by compiler module that you installed. Ex.

C:\Qt\Qt5.9.2\5.9.2\msvc2015_64\translations

I'm working on linguist_it language.

**Comment by bovirus** [comment]
@lelegard 

Could you check please?

**Comment by bovirus** [comment]
@lelegard 

No answer?
I can provide all languages to include in master build.

**Comment by bovirus** [comment]
@lelegard 
Could you please update it? Thanks.

**Comment by lelegard** [comment]
Fixed in [5.10.0](https://github.com/lelegard/qtlinguist-installers/releases/tag/v5.10.0)

**Comment by bovirus** [comment]
@lelegard 

Thanks.
