### ISSUE TITLE
Run powershell script by command line

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#12]
@lelegard 

How can run powershell from MSDOS prompt but the standard command (ex. form windows sub-folder)

**powershell -file build-windows.ps1**

didn't work. Just works

**_powershell build-windows.ps1_**

How can run this .ps1 powershell script without pause at the end of compilation?
I want to create a dos batch that can help user to compile exe/zip file.

**Comment by lelegard** [comment]
With all due respect, I think you do it the wrong way. Invoking powershell from DOS is an anachronism. Powershell was designed to _replace_ DOS, completely. System administrators implement their automation directly using powershell. I never use DOS command windows, just powershell command windows. And you can run powershell scripts directly from the explorer. Etc. See the numerous tutorials and books about powershell.

The pause is done by default so this is more convenient when you just run the script from the explorer. To bypass it, use option -NoPause. See the README file.

**Comment by bovirus** [comment]
@lelegard 

Could be.

I believe that for most novice/basic users (not developers) it's more clear and common make a double click on dos batch like windows-compile.bat that invoke powershell.

**Comment by lelegard** [comment]
To execute the powershell script from explorer, right-click on it and select "Execute".

Like most users, I configured explorer to execute a powershell script by simply double-clicking on it (like a dos batch file) using the following registry entry:

~~~
[HKEY_CLASSES_ROOT\Microsoft.PowerShellScript.1\shell\open\Command]
@="\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" -ExecutionPolicy RemoteSigned -File \"%1\""
~~~

Should I add that, to solve all that mess, my main machine is now a Mac, Windows running in a VM only when I need it :)

**Comment by pablovillaronga76** [comment]
Hi all , I tried that and Still have execution policy blocked , i enroll myself my workstation to Azure , i cannot believe is related , there no GPO yet in place I will look for the keys in registry to modifyf
