### ISSUE TITLE
Change file name of standalone zip file

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#13]
@lelegard 

I propose to change the standard output zip file name removing Standalone.

in the .ps1 powershell script

    # Build standalone installer.
    $ZipInstaller = (Join-Path $InstallerDir "QtLinguist-$Version-Standalone.zip")

to

    # Build standalone installer.
    $ZipInstaller = (Join-Path $InstallerDir "QtLinguist-$Version.zip")

Because is clear that zip is standalone (portable) program.

**Comment by lelegard** [comment]
This is a matter of taste. Honestly, I do not care at all. But if I do it, someone else will say "_could you please make it clear that the zip file is not a compressed installer but a standalone / portable archive_".

I don't want to enter such endless debate (are you vi or emacs, bash or zsh, c++ or java, python or ruby, etc) If you do not like the name, just change it. I won't change the script. Sorry
