### ISSUE TITLE
QT-Linguist 5.11.1 - Release

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#16]
Hi.

QT release SDK 5.11.1.

Could you please QT-Linguist archive?

Thanks.

**Comment by lelegard** [comment]
The purpose of the project is to provide open source scripts for anyone to generate installers, not necessarily to regenerate myself all minor versions. The subject has been reported several times to Qt. In a recent rebirth of the discussion, [it was said that 5.11 will be good for years](https://bugreports.qt.io/browse/QTBUG-55936?focusedCommentId=409724&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-409724).
