### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by imalyavskiy** [lelegard/qtlinguist-installers#24]
Is there any reason why Russian language is missing from the installer's language list?

**Comment by lelegard** [comment]
Do you mean the Windows installer program or the installed Qt Linguist?

In the case of the installer binary, Russian is listed [here](https://github.com/lelegard/qtlinguist-installers/blob/master/windows/qtlinguist.nsi#L126) in the NSIS installer script. NSIS, the installer framework, is then responsible for embedding the corresponding localised strings. That being said, I do not speak 56 of the 58 listed languages, Russian included. So, I cannot check the effectiveness of all languages. I rely on NSIS for this.

In the case of the installed Qt Linguist, we start from a full Qt installation and the build script gathers all installed languages [here](https://github.com/lelegard/qtlinguist-installers/blob/master/windows/build-windows.ps1#L365). If Russian is installed, the corresponding translation files for Qt Linguist should be grabbed with the rest of the languages.
