### ISSUE TITLE
Mention official release in Readme

### ISSUE THREAD

**Issue by Niko-O** [lelegard/qtlinguist-installers#28]
Since 2019, there is an official download for a standalone Linguist installer: https://download.qt.io/linguist_releases/ It would be awesome if you could mention this in the readme.

Ideally, Qt would link to that from their download page, but they [clearly don't give a shit](https://bugreports.qt.io/browse/QTBUG-97510). This repository is the second search result for "qt linguist download" on Google, so you could do the world a big one by making the release actually findable.

**Comment by lelegard** [comment]
Thanks @Niko-O for pointing this. I updated the project status in the README file and added a pointer to the official installer.
