### ISSUE TITLE
build-windows.ps1 - select vcredistr based on x86/x64 platform 

### ISSUE THREAD

**Issue by bovirus** [lelegard/qtlinguist-installers#5]
Hi.

Could you please modify the PowerShell script build-windows.ps1 to use vcredist_msvc2015_x64.exe or vcredist_msvc2015_x86.exe basing on which plaform use to create the qtlinguist exe file?

Currently in standard installation (with both vcredist_msvc2015_x64.exe and vcredist_msvc2015_x86.exe files) the script failed.

I believe that the script should 

- Check if user QTLinguist from QT SDK x64 system it should use vcredist_msvc2015_x64.exe 
- Check if user QTLinguist from QT SDK x86 system it should use vcredist_msvc2015_x86.exe 

I believe that the installer should have a name

QTLinguist-x.x.x-x86.exe if use QTSDK x86 files
QTLinguist-x.x.x-x64.exe if use QTSDK x64 files

I found that the script ps1 available here

https://github.com/lelegard/qtlinguist-installers/tree/master/windows

just create the exe file and seems less updated than the script available here

https://github.com/lelegard/qtlinguist-installers/releases

selecting 5.9.0 source code

Why the script in master repository create just exe installer and not zip standalone file?

I propose to change in teh full script (the script that create also the zi8p standalone)

    $ZipInstaller = (Join-Path $InstallerDir "QtLinguist-$Version-Standalone.zip")

with

    $ZipInstaller = (Join-Path $InstallerDir "QtLinguist-Standalone-$Version.zip")

to have the file

QTLInguist-x.x.x-exe
QTLinguist-x.x.x-Standalone.zip

Thanks.

**Comment by lelegard** [comment]
Hi,

Qt Linguist for Windows is a 32-bit executable. It needs the 32-bit vcredist, not the 64-bit one, even on 64-bit platforms. This is why the script always embeds the 32-bit release and never the 64-bit one.

I just created the installers for Qt 5.9.1 without modifying a single line of the script. The installer is built and it installs correctly on a 64-bit Windows 10. I have no 32-bit Windows system to test, though.
